### ISSUE TITLE
[BUG] Fails to parse function arguments correctly

### ISSUE THREAD

**Issue by TheOtterlord** [talpalang/talpa#1]
While working on talpa, I ran into an issue where the arguments fail to parse properly. I'm not quite sure why.

Output

```
Functions: [Function { name: Some("empty"), args: [], body: Actions { list: [] } }, Function { name: Some("take_args"), args: [("a", Type { name: "int, b int" })], body: Actions { list: [] } }, Function { name: Some("main"), args: [], body: Actions { list: [FunctionCall(ActionFunctionCall { name: "empty", arguments: [] })] } }]
```

My code:

```talpa
fn empty() {}

fn take_args(a int, b int) {}

fn main() { empty() }
```

**Comment by mjarkk** [comment]
Thanks will look into this,  
Now i'm seeing this debug output it might be also cool if we print some more formatted data so we can better search what the problem is.

**Comment by TheOtterlord** [comment]
Good idea. This will help a lot as we add more things to talpa.
