### ISSUE TITLE
switch or match

### ISSUE THREAD

**Issue by mjarkk** [talpalang/talpa#18]
I Think we should also add some sort of a switch logic to the language.  
We could add oldschool switch logic here but i must say i really enjoy the rust match logic.  

Sadly the match statement is kinda special to rust as far as i can see but this does not have to be an issue because a match statement is simply said a more advanced `if else if else if ...`.  
If we would have support for parsing match statements we could add a helper function that converts a match to a `if else if ..` or switch if the match is simple.

**Comment by TheOtterlord** [comment]
I agree. A `match` statements will be so much better, in fact I never used `switch` as I found it a bit pointless, but when coding in rust, I now always use `match` where applicable.

**Comment by mjarkk** [comment]
Cool lets use match then :)

**Comment by TheOtterlord** [comment]
Great. I've added it to the docs here: #19
