### ISSUE TITLE
[Feature] Comparison Object

### ISSUE THREAD

**Issue by TheOtterlord** [talpalang/talpa#48]
**Describe the enhancement you'd like**
When using the `if` action, the `ActionAssignment` is being used to match two values. This is preventing two non-named variables from being compared (such as two numbers or strings). It is also causing the code generation to incorrectly generate the `if` statement and the same thing is happening with my working version of `match`. 

I've included some use cases that are not working. Hopefully these illustrate the problem.

<details>
<summary>Case 1: Variable Comparison</summary>

**Input**
```talpa
if a == b {
}
```

**Expected**
```go
if a == b {
}
```

**Actual**
```talpa
if a = b {
}
```
</details>

<details>
<summary>Case 2: Number Comparison (invalid number)</summary>

**Input**
```talpa
if 1 == 0 {
}
```

**Expected**
```go
if 1 == 0 {
}
```

**Actual**
```log
Error in file: example.tp
7:
8:   if 1 == 0 {
            ^-- Invalid number
9:   }
Unable to compile file, 1 errors occurred
```
</details>

<details>
<summary>Case 2: Number Comparison (unexpected char)</summary>

**Input**
```talpa
if 10 == 0 {
}
```

**Expected**
```go
if 10 == 0 {
}
```

**Actual**
```log
Error in file: example.tp
9:
10:   if 10 == 0 {
               ^-- Unexpected char: =
11:   }
Unable to compile file, 1 errors occurred
```
</details>

My recommended enhancement is a new `Action` designed to handle only comparisons. It would take an `Action`, a comparison type (`==`, `!=`, etc) and a second `Action`. Any if statements only using a single action (such as `if true {}` or `if my_truth_val {}`) would just use the statics. I'm quite busy over the next few days which is why I thought I'd raise this as an issue rather than implement it myself. I'll try to keep working on the `match` implementation, but this really needs to be implemented before I can make any further progress.

**Comment by mjarkk** [comment]
Ya we indeed are missing that, will add it soon :)
