### ISSUE TITLE
Add a Ci to the project (github actions) 

### ISSUE THREAD

**Issue by mjarkk** [talpalang/talpa#5]
As everything is written test based we might want to add a CI to check the MRs to add a extra layer of security.  
For a start we could just check if the code is compilable but later we could also require the tests to pass.  

Github actions look very easy to use though using the free plan you can use a maximum of 2000 minutes per month  
I think it takes around 1m to compile this program without any cache so 2000m ~= 2000actions  

Alternatively we have a few options:  
- circleci: 250 minutes per week
- self hosted:  Lots of options here, github actions, drone, etc..  

@TheOtterlord what do you think?

**Comment by TheOtterlord** [comment]
I think the Rust github action would be the obvious thing to start with. I’ve not used actions before, but it looks good. I think the Rust action builds and tests the PR.

**Comment by TheOtterlord** [comment]
The Rust one is in the recommended actions for this repo: https://github.com/talpalang/talpa/actions/new

**Comment by mjarkk** [comment]
Oke, i've added it
