### ISSUE TITLE
Code Language to use in markdown files

### ISSUE THREAD

**Issue by mjarkk** [talpalang/talpa#8]
I was working a bit on the documentation and found it really annoying to have no syntax highlighting so i experimented a bit with some other languages to see if they would highlight our language correctly.  

vb
```vb
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```
java
```java
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```
ts
```ts
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```
go
```go
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```
cpp
```cpp
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```
coffee
```coffee
fn main() []struct{a string} {
    let result = add(2, 4)
    return result
}
```

This is how they look in a code editor:
![Screenshot from 2020-07-12 19-23-49](https://user-images.githubusercontent.com/15320763/87252680-5127c500-c475-11ea-9310-b4a4b6da46bd.png)

Should we use one of these in our documentation or just leave the code as it without any highlighting.

**Comment by TheOtterlord** [comment]
I think that CPP looks the best inside the editor and on GitHub, but TypeScript and Coffee looks similar. 

I actually wanted to quickly mention that I have started the language-talpa extension repository. I was also looking at some GitHub documentation and if we get a few hundred repositories using Talpa, we will be able to submit a pull request to one of the github org repos and add language-talpa's syntax highlighter to GitHub!

I know we are no where near that stage yet, but could be something to consider in the future. For now I think CPP, TypeScript or Coffee.

**Comment by mjarkk** [comment]
Sounds good lets use CPP for now.
